### ISSUE TITLE
Attempted to read an unowned reference but the object was already deallocated

### ISSUE THREAD

**Issue by teonji** [kvyatkovskys/KVKCalendar#29]
I use your component in a NavigationView page detail.
When I go back into list and the minute changes, the component still call movingCurrentLineHour throwing 'Fatal error: Attempted to read an unowned reference but the object was already deallocated' in TimelineView:282.
How can I catch this? It is possible to fix or did I do something wrong?

**Comment by kvyatkovskys** [comment]
Hi, I'm know about this issue and working on supporting SwiftUI (for UIKit it works fine 🤔).
Perhaps, the issue is with the timer in the main loop 🤔

**Comment by teonji** [comment]
yeah, i think so..but unfortunately I'm not an expert!
now I just forked the project and disabled that function!
Amazing project man 😉

**Comment by kvyatkovskys** [comment]
The issue is fixed (v. 0.2.3)

**Comment by teonji** [comment]
unluckily it still happens to me 😔

**Comment by kvyatkovskys** [comment]
You need to configure `CalendarView` for SwiftUI as described [here ](https://github.com/kvyatkovskys/KVKCalendar#usage-for-swiftui)

**Comment by teonji** [comment]
i followed your instruction and i've configured CalendarView as I described https://github.com/kvyatkovskys/KVKCalendar/issues/32 but timer still throw the error when I use CalendarView in a NavigationView's destination page 😞
did I do something wrong again?
thanks

**Comment by anandabayu** [comment]
I'm using UIKit and this issue still appear

**Comment by kvyatkovskys** [comment]
What version do you use?)

**Comment by anandabayu** [comment]
> What version do you use?)

I use pod, pod 'KVKCalendar' so I guess it the latest version
